### ISSUE TITLE
Failed install 

### ISSUE THREAD

**Issue by oliveiraeduardo** [albertorestifo/atom-spotify2#6]
During the package installation, the following error occurs:

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Users\admin\AppData\Local\atom\app-1.0.0\resources\app\apm\bin\\node.exe" "C:\Users\admin\AppData\Local\atom\app-1.0.0\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\admin\.atom\.apm\.apmrc" "--userconfig" "C:\Users\admin\.atom\.apmrc" "install" "C:\Users\admin\AppData\Local\Temp\d-115529-8236-ykq2rc\package.tgz" "--target=0.22.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: atom-spotify2@2.1.2
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: ia32

**Comment by albertorestifo** [comment]
Not an issue: This packages uses AppleScript to interact with Spotify and it only works in OS X.

Feel free to contribute if you want to integrate Windows support.

**Comment by albertorestifo** [comment]
See #5
